spring:
  datasource:
    url: jdbc:mysql://localhost/fastned
    username: fastneduser
    password: fastneduserpw
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
security:
  user:
    name: fastned-documentatie-secure
    password: fastned-documentatie-secure-pw
server:
  port: 8082